WebApplication9/Models/ManageViewModels.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IdentitySample.Models
{
    public class IndexViewModel
    {
        [Display(Name = "Total Submitted")]
        public double TotalWithVoid { get; set; }

        [Display(Name = "Total Void")]
        public int Void { get; set; }

        [Display(Name = "Total Rejected")]
        public int Rejected { get; set; }

        public double Result { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Password)]
        [Display(Name = "Current Password")]
        public string OldPassword { get; set; }

        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"(?=.*\d)(?=.*[a-z]).{6,15}", ErrorMessage = "Password must be at least 6 characters long, contain one lowercase letter and one digit.")]
        [DataType(DataType.Password)]
        [Display(Name = "New Password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm New Password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

WebApplication9/Controllers/ManageController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication9.Data;
using WebApplication9.Data.Helpers;
using WebApplication9.Helpers;
using WebApplication9.Repository;

namespace IdentitySample.Controllers
{
    [Authorize]
    public class ManageController : Controller
    {
        private IRepository repo;

        private MyUserManager _userManager;

        public ManageController(IRepository repo)
        {
            this.repo = repo;
        }

        public ManageController(MyUserManager userManager)
        {
            UserManager = userManager;
        }

        
        public MyUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<MyUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Index
        public async Task<ActionResult> Index()
        {
            var user = await GetCurrentUser();
            double result;
            var myRequisitions = repo.GetCurrentUserRequisitions(user);

            double positive = myRequisitions.Where(x => x.Status == StatusEnum.Complete || x.Status == StatusEnum.Approved || x.Status == StatusEnum.Aproved_CFO).ToList().Count;
            int voidReq = myRequisitions.Where(x => x.Status == StatusEnum.Void).ToList().Count;
            int rejected = myRequisitions.Where(x => x.Status == StatusEnum.Rejected || x.Status == StatusEnum.Rejected_CFO).ToList().Count;
            double total = positive + rejected;
            double totalWithVoid = myRequisitions.ToList().Count;

            if (positive > 0)
                result = Math.Round((positive / total) * 100, 1, MidpointRounding.AwayFromZero);
            else
                result = 0;
           
            var model = new IndexViewModel
            {
                Rejected = rejected,
                Void = voidReq,
                Result = result,
                TotalWithVoid = totalWithVoid,
            };
            return View(model);
        }

        private async Task<MyUser> GetCurrentUser()
        {
            long currentUserId = long.Parse(User.Identity.GetUserId());
            var user = await UserManager.FindByIdAsync(currentUserId);
            return user;
        }

        //
        // GET: /Manage/ChangePassword
        public ActionResult ChangePassword()
        {
            return View();
        }

        //
        // POST: /Account/Manage
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePasswordAsync(long.Parse(User.Identity.GetUserId()), model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(long.Parse(User.Identity.GetUserId()));
                if (user != null)
                {
                    await SignInAsync(user, isPersistent: false);
                }
                return RedirectToAction("Index");
            }
            AddErrors(result);
            return View(model);
        }

        #region Helpers
        // Used for XSRF protection when adding external logins
        private const string XsrfKey = "XsrfId";

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private async Task SignInAsync(MyUser user, bool isPersistent)
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie, DefaultAuthenticationTypes.TwoFactorCookie);
            AuthenticationManager.SignIn(new AuthenticationProperties { IsPersistent = isPersistent }, await user.GenerateUserIdentityAsync(UserManager));
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private bool HasPassword()
        {
            var user = UserManager.FindById(long.Parse(User.Identity.GetUserId()));
            if (user != null)
            {
                return user.PasswordHash != null;
            }
            return false;
        }

        private bool HasPhoneNumber()
        {
            var user = UserManager.FindById(long.Parse(User.Identity.GetUserId()));
            if (user != null)
            {
                return user.PhoneNumber != null;
            }
            return false;
        }

        public enum ManageMessageId
        {
            AddPhoneSuccess,
            ChangePasswordSuccess,
            SetTwoFactorSuccess,
            SetPasswordSuccess,
            RemoveLoginSuccess,
            RemovePhoneSuccess,
            Error
        }

        #endregion
    }
}

WebApplication9/Controllers/RequisitionController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication9.Data;
using WebApplication9.Helpers;
using PagedList;
using WebApplication9.Models;
using System.Collections.Generic;
using WebApplication9.Data.Helpers;
using System.Web.Script.Serialization;
using WebApplication9.Repository;

namespace WebApplication9.Controllers
{
    [Authorize]
    public class RequisitionController : Controller
    {
        private IRepository repo; 

        private static List<ItemCategory> iCategories;
        private static long _requis;

        private const int minExplanationLength = 10; // for dm and cfo to fill explanation
        private const int pageSize = 3; // controls pagination - items per page
        private const int approvalLimit = 3000;

        private MyUserManager _userManager;

        public RequisitionController(IRepository repo)
        {
            this.repo = repo;
        }

        public RequisitionController(MyUserManager userManager, MyRoleManager roleManager)
        {
            UserManager = userManager;
        }

        public MyUserManager UserManager
        {
            get{ return _userManager ?? HttpContext.GetOwinContext().GetUserManager<MyUserManager>(); }
            private set{ _userManager = value; }
        }

        public ActionResult Create()
        {
            var req = new Requisition();

            ViewBag.Divisions = repo.GetActiveDivisions();
            ViewBag.ItemCategories = repo.GetActiveItemCategories();

            iCategories = ViewBag.ItemCategories;

            return View(req);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Requisition requisition)
        {
            if (ModelState.IsValid && requisition.Items.Count > 0)
            {
                var user = await GetCurrentUser();
                TimeZoneInfo easternTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
                TimeSpan offset = easternTimeZone.GetUtcOffset(DateTime.Now); //fixes the date offset

                requisition.CFO_approval = false; // trigger for CFO approval

                requisition.User_Id = user.Id;
                requisition.Requisitioned_By = user.First_Name + " " + user.Last_Name;
                requisition.Status = StatusEnum.Submitted;
                requisition.Date_Created = DateTime.Now.Add(offset);

                //to-do
                //need to encapsulate this business logic to a service layer
                foreach (var item in requisition.Items) //checking every item in the req to see if any are over the limit
                {
                    if (item.Price * item.Quantity > approvalLimit)
                        requisition.CFO_approval = true;
                }

                repo.AddRequisition(requisition);
                
                repo.AddFiles(Request, user, requisition);

                _requis = requisition.RequisitionId; //holds submitted requisition to refer in the display view

                SendEmailNotification(requisition, user); //sends email to the DM that requisition from user x was submitted

                return RedirectToAction("Display");
            }

            ViewBag.Divisions = repo.GetActiveDivisions();
            ViewBag.ItemCategories = repo.GetActiveItemCategories();

            return View(requisition);
        }

        private void SendEmailNotification(Requisition requisition, MyUser user)
        {
            var currentRequisitionDepartment = repo.GetCurrentRequisitionDepartment(requisition);
            var departmentManager = UserManager.FindById((long)currentRequisitionDepartment.ManagerId);
            string targetEmail = departmentManager.Email;

            var email = new NewRequisitionEmail
            {
                To = targetEmail,
                Recepient = departmentManager.First_Name,
                UserName = user.First_Name + " " + user.Last_Name
            };

            email.Send();
        }

        //calls a partial item view that is triggered when user click add another item in the create view
        public ActionResult ItemEntryRow()
        {
            ViewBag.ItemCategories = iCategories;
            return PartialView("_ItemEntryEditor", new Item());
        }

        //displays a requisition when user submits a req
        public ActionResult Display()
        {
            var requisitionToDisplay = repo.GetRequisition(_requis);
            return View(requisitionToDisplay);
        }

        //populates req files and calls a file partial view with this data
        public PartialViewResult Attachments(int id)
        {
            List<WebApplication9.Data.File> files = repo.GetFiles(id);
            return PartialView(files);
        }

        public FileResult Download(string link, string name)
        {
            return File(link, MediaTypeNames.Application.Octet, name);
        }

        //controls print action
        public async Task<ActionResult> Print(int id)
        {
            var user = await GetCurrentUser();
            Requisition reqToPrint = null;

            //if it is a regualr user or a department manager - limit the query to navigate only user's own requisitions
            //simple users shouldn't be able to navigate to someone else's print view via the url
            if (user.Roles.Count != 0)
                reqToPrint = repo.GetRequisition(id);
            else
                reqToPrint = repo.GetCurrentUserRequistion(id, user);

            if (reqToPrint == null)
                return HttpNotFound();

            return View(reqToPrint);
        }

        //controls void req action, works similar to the print action
        public async Task<ActionResult> Void(int id)
        {
            var user = await GetCurrentUser();
            Requisition reqToVoid = null;

            //if it is a regular user - limit the query to navigate only user's own requisitions
            if (user.Roles.Count != 0)
                reqToVoid = repo.GetRequisition(id);
            else
                reqToVoid = repo.GetCurrentUserRequistion(id, user);

            if (reqToVoid != null)
            {
                reqToVoid.Status = StatusEnum.Void;
                repo.Save();
            }
            else
                return HttpNotFound();

            return Json("Success", JsonRequestBehavior.AllowGet);
        }

        public ActionResult UploadError(){
            return View();
        }

        //controls CFO review action
        [Authorize(Roles = "Admin, Chief Financial Officer")]
        public async Task<ActionResult> ReviewCFO(int? page)
        {
            var user = await GetCurrentUser();
            int pageNumber = (page ?? 1);

            var reqsToReview = repo.GetCFORequisitions(pageNumber, pageSize);

            if (Request.IsAjaxRequest())
            {
                return PartialView("Review", reqsToReview);
            }

            return View(reqsToReview);
        }

        [HttpPost]
        public async Task<JsonResult> ReviewCFO(int id, string decision, string explanation)
        {
            var currentReq = repo.GetRequisition(id);
            var user = await GetCurrentUser();

            if (decision == "approve")
                currentReq.Status = StatusEnum.Aproved_CFO;
            else
                currentReq.Status = StatusEnum.Rejected_CFO;

            currentReq.CFO_Decision_By = user.First_Name + " " + user.Last_Name;
            currentReq.CFO_Explanation = explanation;
            repo.Save();
            return Json("Success", JsonRequestBehavior.AllowGet);
        }

        //controls DM review action
        [Authorize(Roles = "Admin, Department Manager")]
        public async Task<ActionResult> Review(int? page)
        {
            var user = await GetCurrentUser();
            int pageNumber = (page ?? 1);

            var reqsToReview = repo.GetRequisitionsToReview(user, pageNumber, pageSize);

            if (Request.IsAjaxRequest())
            {
                return PartialView("Review", reqsToReview);
            }

            return View(reqsToReview);
        }

        [HttpPost]
        public async Task <ActionResult> Review(int id, string decision, string explanation)
        {
            if (explanation.Length >= minExplanationLength){
                var currentReq = repo.GetRequisition(id);
                var user = await GetCurrentUser();

                if (decision == "approve")
                    currentReq.Status = StatusEnum.Approved;
                else
                    currentReq.Status = StatusEnum.Rejected;

                currentReq.Explanation = explanation;
                currentReq.Decision_By = user.First_Name + " " + user.Last_Name;
                
                repo.Save();
                return Json(String.Empty, JsonRequestBehavior.AllowGet);
            }
            return View();
        }

        public async Task<ActionResult> MyRequisitions(int? page)
        {
            int pageNumber = (page ?? 1);

            var user = await GetCurrentUser();

            var myRequisitions = repo.GetCurrentUserRequisitions(user, pageNumber, pageSize);

            if (Request.IsAjaxRequest())
                return PartialView("MyRequisitions", myRequisitions);

            return View(myRequisitions);
        }

        [Authorize(Roles = "Admin, Purchasing Department")]
        public ActionResult Manage(int? page)
        {
            int pageNumber = (page ?? 1);

            var reqsToManage = repo.GetApprovedRequisitions(pageNumber ,pageSize);

            if (Request.IsAjaxRequest())
                return PartialView("Manage", reqsToManage);

            return View(reqsToManage);
        }

        [HttpPost]

WebApplication9/Views/Requisition/Attachments.cshtml
@model List<WebApplication9.Data.File>

@Html.EditorForModel()

WebApplication9/Views/Requisition/Create.cshtml
@model WebApplication9.Data.Requisition
@{ ViewBag.Title = "Create Requisition"; }


@using (Html.BeginForm("Create", "Requisition", FormMethod.Post,
      new { enctype = "multipart/form-data", @id = "mainForm" }))
{
    <table class="flatTable">
        <tr class="titleTr">
            <td colspan="5">TOTAL <span id="cool">$0</span></td>
        </tr>
        <tr>
            <td class="headingTr">
                <span class="required">*</span>@Html.LabelFor(model => model.Account.Department.Division.Name)
                <div>
                    @Html.DropDownList("Divisions", new SelectList(ViewBag.Divisions, "Id", "Name"), "---Please Select", new { @class = "custom-input  form-control", @id = "division" })
                </div>
            </td>

            <td class="headingTr department">
                <span class="required">*</span>@Html.LabelFor(model => model.Account.Department.Name)
                <div>
                    @Html.DropDownListFor(model => model.DepartmentId, new SelectList(String.Empty, "Value", "Text"), "", new { @class = "custom-input  form-control", @id = "department" })
                    @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger valid" })
                </div>
            </td>
            <td class="headingTr account">
                <span class="required">*</span>@Html.LabelFor(model => model.Account.Name)
                <div>
                    @Html.DropDownListFor(model => model.AccountId, new SelectList(String.Empty, "Value", "Text"), "", new { @class = "custom-input  form-control", @id = "account" })
                    @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger valid" })
                </div>

            </td>
            <td></td>
            <td></td>
        </tr>
    </table>

    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()

    <div id="itemEditor">
        @if (Model.Items.Count <= 1)
        {
            Html.RenderPartial("_ItemEntryEditor", new WebApplication9.Data.Item());
        }
        else
        {
            foreach (var item in Model.Items)
            {
                Html.RenderPartial("_ItemEntryEditor", item);
            }
        }
    </div>

    <div id="addAnother" class="btn-add-item btn-mnu">Add Item</div>

    <div id="reqSubmitBlock">
        <input type="submit" value="Submit" id="proceed" class="btn-mnu btn-default" />

        <a href='@Url.Action("MyRequisitions", "Requisition")'>
            <span class="btn-mnu btn-custom" id="cancel">Cancel</span>
        </a>
    </div>
}

@section Scripts {
    <script type="text/javascript" src="~/Scripts/_js_loadContentCreate.js"></script>
    <script type="text/javascript" src="~/Scripts/_js_AddAnother.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication9/Views/Requisition/Display.cshtml
@model WebApplication9.Data.Requisition
@{ ViewBag.Title = "Requsition Submitted"; }

<h5>Your requisition is successfully submitted.</h5>

@Html.EditorForModel(Model)

<script src="~/Scripts/jquery.collapsiblepanel.js" type="text/javascript"></script>

WebApplication9/Views/Requisition/ItemEntryEditor.cshtml
@model WebApplication9.Data.Item

<div class="container-item holder1" id="reqToCount">
   
    @using (Html.BeginCollectionItem("Items"))
    {
        <span class="icono-trash remove-item"></span>
        <div class="row-main-inline">
            <span>*</span>
            @Html.LabelFor(model => model.ItemCategory.Name, new { @class = "control-label" })
            <div class="row-contents">
                @Html.DropDownListFor(model => model.ItemCategoryId, new SelectList(ViewBag.ItemCategories, "ItemCategoryId", "Name"), "---Please Select", new { @class = "custom-input  form-control" })
                @Html.ValidationMessageFor(model => model.ItemCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="row-main-inline">
            @Html.LabelFor(model => model.BuyFrom, new { @class = "control-label" })

            <div class="row-contents">
                @Html.TextBoxFor(model => model.BuyFrom, new { @class = "custom-input form-control inp-b", Value = "", autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.BuyFrom, "", new { @class = "text-danger valid" })
            </div>
        </div>

        <div class="row-main-inline">
            <span>*</span>
            @Html.LabelFor(model => model.Quantity, new { @class = "control-label" })
            <div class="row-contents">
                @Html.TextBoxFor(model => model.Quantity, new { @class = "qty custom-input form-control inp-b", Value = "", autocomplete = "off" }) 
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger valid" })
            </div>
        </div>

        <div class="row-main-inline">
            <span>*</span>
            @Html.LabelFor(model => model.Price, new { @class = "control-label" })

            <div class="row-contents">
                @Html.TextBoxFor(model => model.Price, new { @class = "price custom-input form-control inp-b", @id = "zzz", Value = "", autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger valid" })
            </div>
        </div>
        
        <div class="container-item">
            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.Description, new { @class = "control-label" })

                <div class="row-contents">
                    @Html.TextAreaFor(model => model.Description, new { @class = "textarea-custom custom-input form-control inp-b" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger valid" })
                </div>
            </div>

            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.Just_Statement, new { @class = "control-label" })
                <div class="row-contents">
                    @Html.TextAreaFor(model => model.Just_Statement, new { @class = "custom-input form-control textarea-custom inp-b" })
                    @Html.ValidationMessageFor(model => model.Just_Statement, "", new { @class = "text-danger valid" })
                </div>
            </div>
        </div>
        <div class="totalItem">
            @Html.Label("Total", new { @class = "" })
            @Html.Label("$0", new { @class = "totalEach" })
        </div>

        <input type="file" name="@Html.IdFor(model => model.ItemId)" id="fileInput" data-val-required="Three attached price quotes are required for items over $3000" multiple />
        <span class="field-validation-valid text-danger valid error" data-valmsg-replace="true" data-valmsg-for="@Html.IdFor(model => model.ItemId)"></span>
        
        <div id="attchmnt"></div>
            
        @Html.HiddenFor(x => x.Unique, new { @Value = Html.IdFor(model => model.ItemId).ToString() });
    }
</div>

<script src="~/Scripts/_js_RemoveItem.js" type="text/javascript"></script>

WebApplication9/Views/Requisition/Manage.cshtml
@model PagedList.IPagedList<WebApplication9.Data.Requisition>
@using PagedList.Mvc;
@{ ViewBag.Title = "Manage Requisitions"; }

@if (Model.Count > 0)
{
    @section AddToHead{
        <link href="~/Content/bootbox.css" rel="stylesheet" />
    }
    <div id="hty">
        @if (Model.PageCount > 1)
        {
            <div id="myPager">
                @Html.PagedListPager(Model, page => Url.Action("Manage", new { page = page }), PagedListRenderOptions.PageNumbersOnly)
            </div>
        }

        @Html.EditorFor(model => Model, "ManageTemplate")
    </div>

    <script type="text/javascript" src="~/Scripts/jquery.collapsiblepanel.js"></script>
    <script type="text/javascript" src="~/Scripts/_js_DatePicker.js"></script>
    <script type="text/javascript" src="~/Scripts/_js_Manage.js"></script>
    <script src="~/Scripts/_js_Pagination.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootbox.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/Scripts/_js_bootbox_void.js"></script>

    @Scripts.Render("~/bundles/jqueryval")
}
else
{   <div class="coffee">
        <h5>There are no approved requisitions at the moment...</h5>
        <span class="icono-cup"></span>
    </div>
}

WebApplication9/Views/Requisition/MyRequisitions.cshtml
@model PagedList.IPagedList<WebApplication9.Data.Requisition>
@using PagedList.Mvc;
@{ViewBag.Title = "My Requisitions";}


@if (Model.Count > 0)
{
    @section AddToHead{
        <link href="~/Content/bootbox.css" rel="stylesheet" />
    }

    <div id="hty">
        @if (Model.PageCount > 1)
        {
            <div id="myPager">
                @Html.PagedListPager(Model, page => Url.Action("MyRequisitions", new { page = page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
            </div>
        }

        @Html.EditorFor(model => Model, "MyRequisitionsTemplate")
    </div>

    <script src="~/Scripts/jquery.collapsiblepanel.js" type="text/javascript"></script>
    <script src="~/Scripts/_js_Pagination.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootbox.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/Scripts/_js_bootbox_void.js"></script>
}
else
{
    <div class="discuss">
        <h2>Currently, you don't have any submitted requisitions.</h2>
        <p>If you need help with the form preparation, you can check out <a style="color: #4ECDC4" href="http://www.wvup.edu/about/business-office/purchasing-office/purchasing-procedures/">purchasing procedures</a> for more information,<br /> or contact the purchasing office.</p>
    </div>

    <div class="feed">
        <div style="font-size:8px; text-align: right">
            <a href="http://feed.mikle.com/" target="_blank" style="color:#CCCCCC;">RSS Feed Widget</a>
        </div>
        <script type="text/javascript">document.write('\x3Cscript type="text/javascript" src="' + ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feed.mikle.com/js/rssmikle.js">\x3C/script>');</script>
        <script type="text/javascript">            (function () { var params = { rssmikle_url: "http://feeds.reuters.com/reuters/topNews|http://feeds.reuters.com/reuters/globalmarketsNews|http://feeds.reuters.com/reuters/financialsNews", rssmikle_frame_width: "300", rssmikle_frame_height: "400", frame_height_by_article: "0", rssmikle_target: "_blank", rssmikle_font: "'Trebuchet MS', Verdana, Arial", rssmikle_font_size: "10", rssmikle_border: "on", responsive: "off", rssmikle_css_url: "", text_align: "left", text_align2: "left", corner: "off", scrollbar: "off", autoscroll: "on", scrolldirection: "up", scrollstep: "10", mcspeed: "20", sort: "New", rssmikle_title: "on", rssmikle_title_sentence: "Latest Financial and World News", rssmikle_title_link: "", rssmikle_title_bgcolor: "#435A6B", rssmikle_title_color: "#FFFFFF", rssmikle_title_bgimage: "", rssmikle_item_bgcolor: "#FFFFFF", rssmikle_item_bgimage: "", rssmikle_item_title_length: "55", rssmikle_item_title_color: "#0066FF", rssmikle_item_border_bottom: "on", rssmikle_item_description: "on", item_link: "off", rssmikle_item_description_length: "250", rssmikle_item_description_color: "#666666", rssmikle_item_date: "gl1", rssmikle_timezone: "Etc/GMT", datetime_format: "%b %e, %Y %l:%M:%S %p", item_description_style: "text", item_thumbnail: "full", item_thumbnail_selection: "auto", article_num: "15", rssmikle_item_podcast: "off", keyword_inc: "", keyword_exc: "" }; feedwind_show_widget_iframe(params); })();</script>
    </div>

    <div class="slider-holder">
        <h2>Quick tips</h2>

        <div id="slider1_container" style="position: relative; width: 600px; height: 100px;">
            <!-- Slides Container -->
            <div u="slides" style="cursor: move; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 600px; height: 100px;">
                <div>
                    <p>
                        Anything over $3,000 must have a minimum of three attached price quotes for competitive pricing.  These requisitions also must be approved by the CFO, in addition to the department budget manager.
                    </p>
                </div>
                <div>
                    <p>
                        You can change the order of the line items before submitting the requisition by simply dragging them.
                    </p>
                </div>
                <div>
                    <p>
                        After you submit your requisition, it should be approved by the department manager.
                    </p>
                </div>
            </div>

            <div u="navigator" class="jssorb13" style="bottom: 16px; right: 6px;">
                <!-- bullet navigator item prototype -->
                <div u="prototype"></div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="~/Scripts/jssor.slider.mini.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            var options = {
                $AutoPlay: false,
                $SlideDuration: 700,
                $BulletNavigatorOptions: {
                    $Class: $JssorBulletNavigator$,
                    $ChanceToShow: 2,
                    $AutoCenter: 1,
                    $Steps: 1,
                    $Lanes: 1,
                    $SpacingX: 10,
                    $SpacingY: 10,
                    $Orientation: 1
                }
            };
            var jssor_slider1 = new $JssorSlider$('slider1_container', options);
        });
    </script>
}