WebApplication9/Controllers/ConfigureController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication9.Data;
using WebApplication9.Data.Helpers;
using WebApplication9.Helpers;
using WebApplication9.Repository;

namespace WebApplication9.Controllers
{
    [Authorize(Roles = "Admin, Purchasing Department")]
    public class ConfigureController : Controller
    {
        private IRepository repo;

        public ConfigureController(IRepository repo)
        {
            this.repo = repo;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateAccount()
        {
            GetAccountData();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAccount(Account model)
        {
            if (ModelState.IsValid)
            {
                repo.AddAccount(model);
                return RedirectToAction("Accounts");
            }
            GetAccountData();
            return View(model);
        }

        public ActionResult EditAccount(int id)
        {
            var accountToEdit = repo.GetAccount(id);
            GetAccountData();
            return View(accountToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAccount(Account model)
        {
            if (ModelState.IsValid)
            {
                var oldAccount = repo.GetAccount(model.Id);

                if (model.Status != oldAccount.Status)
                {
                    oldAccount.Status = model.Status;
                    repo.Save();
                }
                else
                {
                    oldAccount.Status = ConfigureStatusEnum.Inactive;
                    repo.AddAccount(model);
                }

                return RedirectToAction("Accounts");
            }
            GetAccountData();
            return View(model);
        }

        public ActionResult Accounts()
        {
            var accounts = repo.GetAccounts();
            return View(accounts);
        }

        public ActionResult CreateDepartment()
        {
            ViewBag.Divisions = repo.GetDivisions();
            ViewBag.Users = repo.GetUsers();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDepartment(Department model)
        {
            if (ModelState.IsValid)
            {
                repo.AddDepartment(model);
                
                return RedirectToAction("Departments");
            }
            ViewBag.Users = repo.GetUsers();
            ViewBag.Divisions = repo.GetDivisions();
            return View(model);
        }

        public ActionResult EditDepartment(int id)
        {
            var departmentToEdit = repo.GetDepartment(id);
            ViewBag.Divisions = repo.GetDivisions();
            ViewBag.Users = repo.GetUsers();
            return View(departmentToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDepartment(Department model)
        {

            if (ModelState.IsValid)
            {
                //find an existing department and set its status to inactive
                var oldDepartment = repo.GetDepartment(model.Id);

                if (model.Status != oldDepartment.Status) // if the status has changed - set the status of a department to the selected one
                {
                    oldDepartment.Status = model.Status;
                    repo.Save();
                }
                else // if we are editing any department info other than the status
                //set the current department status to incative and create an active department with new parameters
                {
                    oldDepartment.Status = ConfigureStatusEnum.Inactive;
                    repo.AddDepartment(model);
                }

                return RedirectToAction("Departments");
            }

            ViewBag.Divisions = repo.GetDivisions();
            ViewBag.Users = repo.GetUsers();
            return View(model);
        }

        public ActionResult Departments()
        {
            var departments = repo.GetDepartments();
            return View(departments);
        }

        public ActionResult CreateFund()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateFund(Fund model)
        {
            if (ModelState.IsValid)
            {
                repo.AddFunds(model);
                return RedirectToAction("Funds");
            }
            return View(model);
        }

        public ActionResult EditFund(int id)
        {
            var fundToEdit = repo.GetFund(id);
            return View(fundToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFund(Fund model)
        {
            if (ModelState.IsValid)
            {
                var oldFund = repo.GetFund(model.Id);

                if (model.Status != oldFund.Status)
                {
                    oldFund.Status = model.Status;
                    repo.Save();
                }
                else
                {
                    oldFund.Status = ConfigureStatusEnum.Inactive;
                    repo.AddFunds(model);
                }

                return RedirectToAction("Funds");
            }
            return View(model);
        }

        public ActionResult Funds()
        {
            var funds = repo.getFunds();
            return View(funds);
        }

        public ActionResult CreateDivision()
        {
            GetDepartmentsViewBag();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDivision(Division model)
        {
            if (ModelState.IsValid)
            {
                repo.AddDivision(model);
                
                return RedirectToAction("Divisions");
            }
            GetDepartmentsViewBag();
            return View(model);
        }

        public ActionResult EditDivision(int id)
        {
            var divisionToEdit = repo.GetDivision(id);

            return View(divisionToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDivision(Division model)
        {

            if (ModelState.IsValid)
            {
                var oldDivision = repo.GetDivision(model.Id);

                if (model.Status != oldDivision.Status)
                {
                    oldDivision.Status = model.Status;
                    repo.Save();
                }
                else
                {
                    oldDivision.Status = ConfigureStatusEnum.Inactive;
                    repo.AddDivision(model);
                }

                return RedirectToAction("Divisions");
            }
            return View(model);
        }

        public ActionResult Divisions()
        {
            var divisions = repo.GetDivisions();
            return View(divisions);
        }

        public JsonResult GetDivisionDepartments(int id)
        {
            var divisionDepartments = repo.GetActiveDivsionDepartments(id);
            var result = Json(divisionDepartments);

            return Json(new SelectList(divisionDepartments, "Id", "Name"));
        }

        private void GetAccountData()
        {
            GetActiveDepartmentsViewBag();

            var funds = repo.GetActiveFunds();
            var divisions = repo.GetActiveDivisions();
            ViewBag.Funds = funds;
            ViewBag.Divisions = divisions;
        }

        private void GetDepartmentsViewBag()
        {
            var departments = repo.GetDepartments();
            ViewBag.Departments = departments;
        }

        private void GetActiveDepartmentsViewBag()
        {
            var departments = repo.GetActiveDepartments();
            ViewBag.Departments = departments;
        }

        public ActionResult CreateItemCategory()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateItemCategory(ItemCategory model)
        {
            if (ModelState.IsValid)
            {
                repo.AddItemCategory(model);
                
                return RedirectToAction("ItemCategories");
            }
            return View(model);
        }

        public ActionResult EditItemCategory(int id)
        {
            var itemCategoryToEdit = repo.GetItemCategory(id);
            return View(itemCategoryToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditItemCategory(ItemCategory model)
        {
            if (ModelState.IsValid)
            {
                var oldItemCategory = repo.GetItemCategory(model.ItemCategoryId);

                if (model.Status != oldItemCategory.Status)
                {
                    oldItemCategory.Status = model.Status;
                    repo.Save();
                }
                else
                {
                    oldItemCategory.Status = ConfigureStatusEnum.Inactive;
                    repo.AddItemCategory(model);
                }

                return RedirectToAction("ItemCategories");
            }
            return View(model);
        }

        public ActionResult ItemCategories()
        {
            var itemCategories = repo.GetItemCategories();
            return View(itemCategories);
        }

	}
}

WebApplication9/Controllers/RolesAdminController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;
using WebApplication9.Data;

namespace IdentitySample.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesAdminController : Controller
    {
        private MyUserManager _userManager;
        private MyRoleManager _roleManager;
        public RolesAdminController()
        {
        }

        public RolesAdminController(MyUserManager userManager,
            MyRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }


        public MyUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<MyUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        
        public MyRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<MyRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        //
        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<MyUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new MyRole(roleViewModel.Name);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

WebApplication9/Views/RolesAdmin/Create.cshtml
@model IdentitySample.Models.RoleViewModel

@{
    ViewBag.Title = "Create Role";
}

<h2>Create Role</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="configure-create-account">
            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                <div class="row-contents">
                    @Html.TextBoxFor(model => model.Name, new { @class = "custom-input form-control inp-b", autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="configure-control">
            <span>
                <input type="submit" value="Create" class="btn-mnu btn-default" />
            </span>
            <a href="@Url.Action("Index", "RolesAdmin")">
                <span>
                    <span class="btn-mnu btn-custom">Back To List</span>
                </span>
            </a>
        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication9/Views/RolesAdmin/Delete.cshtml
@model WebApplication9.Data.MyRole

@{
    ViewBag.Title = "Delete Role";
}

<h3>Are you sure you want to delete this Role? </h3>
<h2>@Html.DisplayFor(model => model.Name)</h2>

<p>Deleting this Role will remove all users from this role. It will not delete the users.</p>

<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <div class="configure-control">
            <span>
                <input type="submit" value="Delete" class="btn-mnu btn-default" />
            </span>
            <a href="@Url.Action("Index")">
                <span>
                    <span class="btn-mnu btn-custom">Back To List</span>
                </span>
            </a>
        </div>
    }
</div>

WebApplication9/Views/RolesAdmin/Details.cshtml
@model WebApplication9.Data.MyRole
@section AddToHead{
    @Styles.Render("~/Content/datatables")
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<table class="data-table display" id="data-table">
    <thead>
        <tr>
            <th>
                List of users in this role
            </th>
            <th class="datatable-nosort"></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in ViewBag.Users)
        {
            <tr>
                <td>
                    @item.UserName
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "UsersAdmin", new { id = item.Id }, null)
                    @Html.ActionLink("Details", "Details", "UsersAdmin", new { id = item.Id }, null)
                    @Html.ActionLink("Delete", "Delete", "UsersAdmin", new { id = item.Id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>

@if (ViewBag.UserCount == 0)
{
    <p>No users found in this role.</p>
}

<div class="configure-control">
    <a href="@Url.Action("Index", "RolesAdmin")">
        <span>
            <span class="btn-mnu btn-custom">Back To List</span>
        </span>
    </a>
</div>

@Scripts.Render("~/bundles/datatables")

<script>
    $(document).ready(function () {
        $('#data-table').DataTable({
            columnDefs: [{
                targets: "datatable-nosort",
                orderable: false
            }]
        });
    });
</script>

WebApplication9/Views/RolesAdmin/Edit.cshtml
@model IdentitySample.Models.RoleViewModel

@{
    ViewBag.Title = "Edit Role";
}

<h2>Edit Role</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="configure-create-account">
            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                <div class="row-contents">
                    @Html.TextBoxFor(model => model.Name, new { @class = "custom-input form-control inp-b", autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="configure-control">
            <span>
                <input type="submit" value="Save" class="btn-mnu btn-default" />
            </span>
            <a href="@Url.Action("Index")">
                <span>
                    <span class="btn-mnu btn-custom">Back To List</span>
                </span>
            </a>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication9/Views/RolesAdmin/Index.cshtml
@model IEnumerable<WebApplication9.Data.MyRole>
@section AddToHead{
    @Styles.Render("~/Content/datatables")
}

<table class="data-table display" id="data-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="datatable-nosort"></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="configure-control">
    <a href="@Url.Action("Create", "RolesAdmin")">
        <span>
            <span class="btn-mnu btn-default">New Role</span>
        </span>
    </a>

    <a href="@Url.Action("Index", "Configure")">
        <span>
            <span class="btn-mnu btn-custom">Back To List</span>
        </span>
    </a>
</div>

@Scripts.Render("~/bundles/datatables")

<script>
    $(document).ready(function () {
        $('#data-table').DataTable({
            columnDefs: [{
                targets: "datatable-nosort",
                orderable: false
            }]
        });
    });
</script>