WebApplication9/Controllers/ConfigureController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication9.Data;
using WebApplication9.Data.Helpers;
using WebApplication9.Helpers;
using WebApplication9.Repository;

namespace WebApplication9.Controllers
{
    [Authorize(Roles = "Admin, Purchasing Department")]
    public class ConfigureController : Controller
    {
        private IRepository repo;

        public ConfigureController(IRepository repo)
        {
            this.repo = repo;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateAccount()
        {
            GetAccountData();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAccount(Account model)
        {
            if (ModelState.IsValid)
            {
                repo.AddAccount(model);
                return RedirectToAction("Accounts");
            }
            GetAccountData();
            return View(model);
        }

        public ActionResult EditAccount(int id)
        {
            var accountToEdit = repo.GetAccount(id);
            GetAccountData();
            return View(accountToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAccount(Account model)
        {
            if (ModelState.IsValid)
            {
                var oldAccount = repo.GetAccount(model.Id);

                if (model.Status != oldAccount.Status)
                {
                    oldAccount.Status = model.Status;
                    repo.Save();
                }
                else
                {
                    oldAccount.Status = ConfigureStatusEnum.Inactive;
                    repo.AddAccount(model);
                }

                return RedirectToAction("Accounts");
            }
            GetAccountData();
            return View(model);
        }

        public ActionResult Accounts()
        {
            var accounts = repo.GetAccounts();
            return View(accounts);
        }

        public ActionResult CreateDepartment()
        {
            ViewBag.Divisions = repo.GetDivisions();
            ViewBag.Users = repo.GetUsers();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDepartment(Department model)
        {
            if (ModelState.IsValid)
            {
                repo.AddDepartment(model);
                
                return RedirectToAction("Departments");
            }
            ViewBag.Users = repo.GetUsers();
            ViewBag.Divisions = repo.GetDivisions();
            return View(model);
        }

        public ActionResult EditDepartment(int id)
        {
            var departmentToEdit = repo.GetDepartment(id);
            ViewBag.Divisions = repo.GetDivisions();
            ViewBag.Users = repo.GetUsers();
            return View(departmentToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDepartment(Department model)
        {

            if (ModelState.IsValid)
            {
                //find an existing department and set its status to inactive
                var oldDepartment = repo.GetDepartment(model.Id);

                if (model.Status != oldDepartment.Status) // if the status has changed - set the status of a department to the selected one
                {
                    oldDepartment.Status = model.Status;
                    repo.Save();
                }
                else // if we are editing any department info other than the status
                //set the current department status to incative and create an active department with new parameters
                {
                    oldDepartment.Status = ConfigureStatusEnum.Inactive;
                    repo.AddDepartment(model);
                }

                return RedirectToAction("Departments");
            }

            ViewBag.Divisions = repo.GetDivisions();
            ViewBag.Users = repo.GetUsers();
            return View(model);
        }

        public ActionResult Departments()
        {
            var departments = repo.GetDepartments();
            return View(departments);
        }

        public ActionResult CreateFund()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateFund(Fund model)
        {
            if (ModelState.IsValid)
            {
                repo.AddFunds(model);
                return RedirectToAction("Funds");
            }
            return View(model);
        }

        public ActionResult EditFund(int id)
        {
            var fundToEdit = repo.GetFund(id);
            return View(fundToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFund(Fund model)
        {
            if (ModelState.IsValid)
            {
                var oldFund = repo.GetFund(model.Id);

                if (model.Status != oldFund.Status)
                {
                    oldFund.Status = model.Status;
                    repo.Save();
                }
                else
                {
                    oldFund.Status = ConfigureStatusEnum.Inactive;
                    repo.AddFunds(model);
                }

                return RedirectToAction("Funds");
            }
            return View(model);
        }

        public ActionResult Funds()
        {
            var funds = repo.getFunds();
            return View(funds);
        }

        public ActionResult CreateDivision()
        {
            GetDepartmentsViewBag();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDivision(Division model)
        {
            if (ModelState.IsValid)
            {
                repo.AddDivision(model);
                
                return RedirectToAction("Divisions");
            }
            GetDepartmentsViewBag();
            return View(model);
        }

        public ActionResult EditDivision(int id)
        {
            var divisionToEdit = repo.GetDivision(id);

            return View(divisionToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDivision(Division model)
        {

            if (ModelState.IsValid)
            {
                var oldDivision = repo.GetDivision(model.Id);

                if (model.Status != oldDivision.Status)
                {
                    oldDivision.Status = model.Status;
                    repo.Save();
                }
                else
                {
                    oldDivision.Status = ConfigureStatusEnum.Inactive;
                    repo.AddDivision(model);
                }

                return RedirectToAction("Divisions");
            }
            return View(model);
        }

        public ActionResult Divisions()
        {
            var divisions = repo.GetDivisions();
            return View(divisions);
        }

        public JsonResult GetDivisionDepartments(int id)
        {
            var divisionDepartments = repo.GetActiveDivsionDepartments(id);
            var result = Json(divisionDepartments);

            return Json(new SelectList(divisionDepartments, "Id", "Name"));
        }

        private void GetAccountData()
        {
            GetActiveDepartmentsViewBag();

            var funds = repo.GetActiveFunds();
            var divisions = repo.GetActiveDivisions();
            ViewBag.Funds = funds;
            ViewBag.Divisions = divisions;
        }

        private void GetDepartmentsViewBag()
        {
            var departments = repo.GetDepartments();
            ViewBag.Departments = departments;
        }

        private void GetActiveDepartmentsViewBag()
        {
            var departments = repo.GetActiveDepartments();
            ViewBag.Departments = departments;
        }

        public ActionResult CreateItemCategory()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateItemCategory(ItemCategory model)
        {
            if (ModelState.IsValid)
            {
                repo.AddItemCategory(model);
                
                return RedirectToAction("ItemCategories");
            }
            return View(model);
        }

        public ActionResult EditItemCategory(int id)
        {
            var itemCategoryToEdit = repo.GetItemCategory(id);
            return View(itemCategoryToEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditItemCategory(ItemCategory model)
        {
            if (ModelState.IsValid)
            {
                var oldItemCategory = repo.GetItemCategory(model.ItemCategoryId);

                if (model.Status != oldItemCategory.Status)
                {
                    oldItemCategory.Status = model.Status;
                    repo.Save();
                }
                else
                {
                    oldItemCategory.Status = ConfigureStatusEnum.Inactive;
                    repo.AddItemCategory(model);
                }

                return RedirectToAction("ItemCategories");
            }
            return View(model);
        }

        public ActionResult ItemCategories()
        {
            var itemCategories = repo.GetItemCategories();
            return View(itemCategories);
        }

	}
}

WebApplication9/Controllers/UserAdminController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication9.Data;
using WebApplication9.Repository;

namespace IdentitySample.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        private MyUserManager _userManager;
        private MyRoleManager _roleManager;

        IRepository repo;

        public UsersAdminController(IRepository repo)
        {
            this.repo = repo;
        }

        public UsersAdminController(MyUserManager userManager, MyRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }


        public MyUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<MyUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        
        public MyRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<MyRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        public async Task<ActionResult> Details(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            var departments = repo.GetDepartments();
            ViewBag.Departments = departments;
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
         {
            if (ModelState.IsValid)
            {
                var user = new MyUser { 
                    UserName = userViewModel.Email, 
                    Email = userViewModel.Email,
                    First_Name = userViewModel.First_Name,
                    Last_Name = userViewModel.Last_Name
                };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "UserName,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.UserName;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        public async Task<ActionResult> Delete(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        public JsonResult GetDivisionDepartments(int id)
        {
            var divisionDepartments = repo.GetActiveDepartments(id);
            var result = Json(divisionDepartments);

            return Json(new SelectList(divisionDepartments, "Id", "Name"));
        }
    }
}

WebApplication9/Views/UsersAdmin/Create.cshtml
@model IdentitySample.Models.RegisterViewModel
@{
    ViewBag.Title = "Create User Account";
}

<h2>Create User Account Manually</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        <div class="configure-create-account">

            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.Email, new { @class = "control-label" })
                <div class="row-contents">
                    @Html.TextBoxFor(model => model.Email, new { @class = "custom-input form-control inp-b" })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.First_Name, new { @class = "control-label" })
                <div class="row-contents">
                    @Html.TextBoxFor(model => model.First_Name, new { @class = "custom-input form-control inp-b" })
                    @Html.ValidationMessageFor(model => model.First_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.Last_Name, new { @class = "control-label" })
                <div class="row-contents">
                    @Html.TextBoxFor(model => model.Last_Name, new { @class = "custom-input form-control inp-b" })
                    @Html.ValidationMessageFor(model => model.Last_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.Password, new { @class = "control-label" })
                <div class="row-contents">
                    @Html.PasswordFor(model => model.Password, new { @class = "custom-input form-control inp-b" })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label" })
                <div class="row-contents">
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "custom-input form-control inp-b" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
    </div>

    <div class="form-group">
        <label>Select User Roles:</label>
        <div>
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </div>
    </div>

    <div class="configure-control">
        <span>
            <input type="submit" value="Create" class="btn-mnu btn-default" />
        </span>
        <a href="@Url.Action("Index")">
            <span>
                <span class="btn-mnu btn-custom">Back To List</span>
            </span>
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication9/Views/UsersAdmin/Delete.cshtml
@model WebApplication9.Data.MyUser

@{
    ViewBag.Title = "Delete User";
}

<h3>Are you sure you want to delete this User?</h3>
<h2>@Html.DisplayFor(model => model.UserName)</h2>

<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="configure-control">
            <span>
                <input type="submit" value="Delete" class="btn-mnu btn-default" />
            </span>
            <a href="@Url.Action("Index")">
                <span>
                    <span class="btn-mnu btn-custom">Back To List</span>
                </span>
            </a>
        </div>
    }
</div>

WebApplication9/Views/UsersAdmin/Details.cshtml
@model WebApplication9.Data.MyUser
@section AddToHead{
    @Styles.Render("~/Content/datatables")
}

<h2>@Html.DisplayFor(model => model.UserName)</h2>

<table class="data-table display" id="data-table">
    <thead>
        <tr>
            <th>
                List of roles for this user
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in ViewBag.RoleNames)
        {
            <tr>
                <td>
                    @item
                </td>
            </tr>
        }
    </tbody>
</table>

@if (ViewBag.RoleNames.Count == 0)
{
    <p>No roles found for this user.</p>
}

<div class="configure-control">
    <a href="@Url.Action("Index", "UsersAdmin")">
        <span>
            <span class="btn-mnu btn-custom">Back To List</span>
        </span>
    </a>
</div>

@Scripts.Render("~/bundles/datatables")

<script>
    $(document).ready(function () {
        $('#data-table').DataTable();
    });
</script>

WebApplication9/Views/UsersAdmin/Edit.cshtml
@model IdentitySample.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit User";
}

<h2>Edit User</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="configure-create-account">
            <div class="row-main-inline">
                <span>*</span>
                @Html.Label("Roles", new { @class = "control-label" })
                <div class="row-contents">
                    <span class=" col-md-10">
                        @foreach (var item in Model.RolesList)
                        {
                            <input type="checkbox" name="selectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                            @Html.Label(item.Value, new { @class = "control-label" })
                        }
                    </span>
                </div>
            </div>

            <div class="row-main-inline">
                <span>*</span>
                @Html.LabelFor(model => model.UserName, new { @class = "control-label" })
                <div class="row-contents">
                    @Html.TextBoxFor(model => model.UserName, new { @class = "custom-input form-control inp-b" })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="configure-control">
            <span>
                <input type="submit" value="Save" class="btn-mnu btn-default" />
            </span>
            <a href="@Url.Action("Index")">
                <span>
                    <span class="btn-mnu btn-custom">Back To List</span>
                </span>
            </a>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication9/Views/UsersAdmin/Index.cshtml
@model IEnumerable<WebApplication9.Data.MyUser>
@section AddToHead{
    @Styles.Render("~/Content/datatables")
}

<table class="data-table display" id="data-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th class="datatable-nosort"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="configure-control">
    <a href="@Url.Action("Create")">
        <span>
            <span class="btn-mnu btn-default">New Account</span>
        </span>
    </a>

    <a href="@Url.Action("Index", "Configure")">
        <span>
            <span class="btn-mnu btn-custom">Back To List</span>
        </span>
    </a>
</div>

@Scripts.Render("~/bundles/datatables")

<script>
    $(document).ready(function () {
        $('#data-table').DataTable({
            columnDefs: [{
                targets: "datatable-nosort",
                orderable: false
            }]
        });
    });
</script>